CREATE TABLE IF NOT EXISTS users(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS banks(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL UNIQUE,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS accounts(
	id INTEGER PRIMARY KEY,
	user_id INTEGER NOT NULL,
	bank_id INTEGER NOT NULL,
	account_id TEXT NOT NULL UNIQUE,
	account_type TEXT,
	plaid_token TEXT NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY(bank_id) REFERENCES banks (id) ON DELETE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users (id)
);