// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Account defines model for Account.
type Account struct {
	AccountId   int    `json:"account_id"`
	AccountType string `json:"account_type"`
}

// BankItem defines model for BankItem.
type BankItem struct {
	BankId   int    `json:"bank_id"`
	BankName string `json:"bank_name"`
}

// FinancialInstitutionsResponse defines model for FinancialInstitutionsResponse.
type FinancialInstitutionsResponse struct {
	Banks []BankItem `json:"banks"`
}

// SaveNewAccountRequest defines model for SaveNewAccountRequest.
type SaveNewAccountRequest struct {
	AccessToken string    `json:"access_token"`
	Accounts    []Account `json:"accounts"`
	BankName    string    `json:"bank_name"`
	UserId      int       `json:"user_id"`
}

// SaveNewBankRequest defines model for SaveNewBankRequest.
type SaveNewBankRequest struct {
	BankName string `json:"bank_name"`
}

// SaveNewBankResponse defines model for SaveNewBankResponse.
type SaveNewBankResponse struct {
	BankId int `json:"bank_id"`
}

// UserAccountInfo defines model for UserAccountInfo.
type UserAccountInfo struct {
	AccessToken string    `json:"access_token"`
	Accounts    []Account `json:"accounts"`
	BankName    string    `json:"bank_name"`
}

// UserFinancialProfile defines model for UserFinancialProfile.
type UserFinancialProfile struct {
	Banks  []UserAccountInfo `json:"banks"`
	UserId *int              `json:"user_id,omitempty"`
}

// SaveBankAccountJSONRequestBody defines body for SaveBankAccount for application/json ContentType.
type SaveBankAccountJSONRequestBody = SaveNewAccountRequest

// SaveNewBankJSONRequestBody defines body for SaveNewBank for application/json ContentType.
type SaveNewBankJSONRequestBody = SaveNewBankRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Save information about a new bank account
	// (POST /v1/bank/accounts)
	SaveBankAccount(c *gin.Context)
	// Get all Financial Institutions
	// (GET /v1/bank/institutions)
	GetFinancialInstitutions(c *gin.Context)
	// Save Financial Institution Information
	// (POST /v1/bank/institutions)
	SaveNewBank(c *gin.Context)
	// Get a user's financial institution information
	// (GET /v1/bank/users/{userID}/banks)
	GetUserFinancialProfile(c *gin.Context, userID string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// SaveBankAccount operation middleware
func (siw *ServerInterfaceWrapper) SaveBankAccount(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SaveBankAccount(c)
}

// GetFinancialInstitutions operation middleware
func (siw *ServerInterfaceWrapper) GetFinancialInstitutions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetFinancialInstitutions(c)
}

// SaveNewBank operation middleware
func (siw *ServerInterfaceWrapper) SaveNewBank(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SaveNewBank(c)
}

// GetUserFinancialProfile operation middleware
func (siw *ServerInterfaceWrapper) GetUserFinancialProfile(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUserFinancialProfile(c, userID)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/bank/accounts", wrapper.SaveBankAccount)
	router.GET(options.BaseURL+"/v1/bank/institutions", wrapper.GetFinancialInstitutions)
	router.POST(options.BaseURL+"/v1/bank/institutions", wrapper.SaveNewBank)
	router.GET(options.BaseURL+"/v1/bank/users/:userID/banks", wrapper.GetUserFinancialProfile)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xVS2/bOBD+K8TsAnsRImcfF+0p2W0DoUAbJOgpCAJGGtuMJVIZjhwYhv57QcqSZYdy",
	"HTQuejItPuZ7zGMNmSkro1GzhWQNNptjKf3yIstMrdktKzIVEiv0G7LdeFC5+8erCiEBpRlnSNBE/X67",
	"05+wTErPoGkiIHyuFWEOyd3wtb2r91F31Tw+Ycbu7UupFylj+RrVo9SLUUh+U8vyCDzdO8NLISQflZY6",
	"U7JItWXFNSuj7Q3aymiLYXh+oRhLv/idcAoJ/BZvHYg38sc9zaaPLInkKojWBvHdyiV+xpeNizf4XKMN",
	"m4nWPrBZoA6I01tyPPYub15BP2xDBLVFGnFwj3V3cvjiAGm0y+qAOk7nUWnemjSjqbIT7FCCHMe+OxkK",
	"9dUibQxI9dT8wn6PKvg2Ix3hvhSvyUxV8cPVty9igNnxuTpWoe6c2liUo81IVa6FQAIX16kVPJcsSqnl",
	"DMW04yfUtteIF0MLiIAVO8a+M4pbpKXKnIZLJNs+d342OZs4zKZCLSsFCfzlP0VQSZ57NeLleeyAxkP3",
	"K9NWhRNSupBpDolPZhers71li5YvTb5yxzOjGdu5IauqUJm/Gz9Zo7cT5nsWhLtXsysuU43+Q1tTHvSf",
	"k8lrRb98+le4F3Mnw9+hE6leykLlgrpIEfwTOucERhJIZFqrbV2WklYbYYRzlErPWMhHU7OQQuOLcOIK",
	"2VVKE20VH1jqCcwwIPoVcnDeQJj9u1hweMB5K3a1+a8mQs3FShDOlGUkzMO5a9/Lhw8BH66QhSwK0eMX",
	"6V7k8cTedOnTJvVw6ByV0eenQTDuZFA6YWvfjKd1UayE/SnlFAaSbotst5ZcV7bx2v2k/zdx3/XHaio4",
	"PFxbJFkiI1lI7tagHFLXKiGCdphBGwH2rYsGNuyPu/sTlmqQR8DX26GDU+RsjrlwXP6wbYfKkaUq7Cl9",
	"9eXZBQ1PNrXjb9N8CwAA//9RlnZypQwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
