// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Account defines model for Account.
type Account struct {
	AccountId   string `json:"account_id"`
	AccountType string `json:"account_type"`
}

// BankItem defines model for BankItem.
type BankItem struct {
	BankId   int    `json:"bank_id"`
	BankName string `json:"bank_name"`
}

// CreateLinkTokenRequest defines model for CreateLinkTokenRequest.
type CreateLinkTokenRequest struct {
	UserId int `json:"user_id"`
}

// CreateLinkTokenResponse defines model for CreateLinkTokenResponse.
type CreateLinkTokenResponse struct {
	Expiration string `json:"expiration"`
	LinkToken  string `json:"link_token"`
}

// ExchangePublicTokenRequest defines model for ExchangePublicTokenRequest.
type ExchangePublicTokenRequest struct {
	BankName    string `json:"bank_name"`
	PublicToken string `json:"public_token"`
	UserId      int    `json:"user_id"`
}

// ExchangePublicTokenResponse defines model for ExchangePublicTokenResponse.
type ExchangePublicTokenResponse struct {
	Accounts []Account `json:"accounts"`
	BankId   int       `json:"bank_id"`
}

// FinancialInstitutionsResponse defines model for FinancialInstitutionsResponse.
type FinancialInstitutionsResponse struct {
	Banks []BankItem `json:"banks"`
}

// SaveNewAccountRequest defines model for SaveNewAccountRequest.
type SaveNewAccountRequest struct {
	AccessToken string  `json:"access_token"`
	Accounts    Account `json:"accounts"`
	BankName    string  `json:"bank_name"`
	UserId      int     `json:"user_id"`
}

// SaveNewBankRequest defines model for SaveNewBankRequest.
type SaveNewBankRequest struct {
	BankName string `json:"bank_name"`
}

// SaveNewBankResponse defines model for SaveNewBankResponse.
type SaveNewBankResponse struct {
	BankId int `json:"bank_id"`
}

// UserAccountInfo defines model for UserAccountInfo.
type UserAccountInfo struct {
	Accounts []Account `json:"accounts"`
	BankName string    `json:"bank_name"`
}

// UserFinancialProfile defines model for UserFinancialProfile.
type UserFinancialProfile struct {
	Banks  []UserAccountInfo `json:"banks"`
	UserId *int              `json:"user_id,omitempty"`
}

// SaveBankAccountJSONRequestBody defines body for SaveBankAccount for application/json ContentType.
type SaveBankAccountJSONRequestBody = SaveNewAccountRequest

// SaveNewBankJSONRequestBody defines body for SaveNewBank for application/json ContentType.
type SaveNewBankJSONRequestBody = SaveNewBankRequest

// ExchangePublicTokenJSONRequestBody defines body for ExchangePublicToken for application/json ContentType.
type ExchangePublicTokenJSONRequestBody = ExchangePublicTokenRequest

// CreateLinkTokenJSONRequestBody defines body for CreateLinkToken for application/json ContentType.
type CreateLinkTokenJSONRequestBody = CreateLinkTokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Save information about a new bank account
	// (POST /v1/bank/accounts)
	SaveBankAccount(c *gin.Context)
	// Get all Financial Institutions
	// (GET /v1/bank/institutions)
	GetFinancialInstitutions(c *gin.Context)
	// Save Financial Institution Information
	// (POST /v1/bank/institutions)
	SaveNewBank(c *gin.Context)
	// Exchange a Plaid Link public_token for an access_token and save the linked accounts
	// (POST /v1/bank/plaid/exchange)
	ExchangePublicToken(c *gin.Context)
	// Create a Plaid Link token so a frontend can launch Plaid Link
	// (POST /v1/bank/plaid/link-token)
	CreateLinkToken(c *gin.Context)
	// Get a user's financial institution information
	// (GET /v1/bank/users/{userID}/banks)
	GetUserFinancialProfile(c *gin.Context, userID string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// SaveBankAccount operation middleware
func (siw *ServerInterfaceWrapper) SaveBankAccount(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SaveBankAccount(c)
}

// GetFinancialInstitutions operation middleware
func (siw *ServerInterfaceWrapper) GetFinancialInstitutions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetFinancialInstitutions(c)
}

// SaveNewBank operation middleware
func (siw *ServerInterfaceWrapper) SaveNewBank(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SaveNewBank(c)
}

// ExchangePublicToken operation middleware
func (siw *ServerInterfaceWrapper) ExchangePublicToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExchangePublicToken(c)
}

// CreateLinkToken operation middleware
func (siw *ServerInterfaceWrapper) CreateLinkToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateLinkToken(c)
}

// GetUserFinancialProfile operation middleware
func (siw *ServerInterfaceWrapper) GetUserFinancialProfile(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUserFinancialProfile(c, userID)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/bank/accounts", wrapper.SaveBankAccount)
	router.GET(options.BaseURL+"/v1/bank/institutions", wrapper.GetFinancialInstitutions)
	router.POST(options.BaseURL+"/v1/bank/institutions", wrapper.SaveNewBank)
	router.POST(options.BaseURL+"/v1/bank/plaid/exchange", wrapper.ExchangePublicToken)
	router.POST(options.BaseURL+"/v1/bank/plaid/link-token", wrapper.CreateLinkToken)
	router.GET(options.BaseURL+"/v1/bank/users/:userID/banks", wrapper.GetUserFinancialProfile)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xX32/bNhD+Vw7cgL1oVbIfL35ru64QNmzBsj0VRXGhzjZriVRJyqkR+H8fSEqyZFOK",
	"2kZ5imJRvO++7zve8YFxVVZKkrSGrR6Y4Vsq0T++5FzV0rrHSquKtBXkX2B48UHk7j97qIitmLFayA07",
	"Jt3r8OJiwTFhmj7VQlPOVu/6m519+j5pP1V3H4lbt/crlLvMUnkJ6g7lbohISEsb0u4z/1JiOQNPu0//",
	"oxiS15rQ0p9C7v5VO5L/0KeaTISs2pAewXUWuV05K5qplDR0GY4+V0KjFUpGtSmE3H2wbovHmeitTfr7",
	"xvC9+cy3KDd0U98Vgk8zMiVGwiq/wyjG5CsI7Ut5FmB2LmN8N471z8JS6R++17RmK/ZdeqqttCmstK2q",
	"YxcZtcZD59JZmZ1M2sWPZfK7kCi5wCKTxgpbO/nMeC5u1/mJdKV4kUkEbBzfLe7pL7pvKBk1DHJOxkxY",
	"oi/CTO6nTfitHusAJUPwEyQ4Or+qZGLWGD21BsGmfPBlPoyF+s+QbgjP5Fo9Q+l8KUGPVI9LoKugG63W",
	"ovjmojknJZLKfO+NFZZbJxrKczJciyo0BPbyJjNgt2ihRIkbgnWbH4jTEQH3Su9YwqywLmPfdOGW9F5w",
	"R9qetAnbXb+4enHlMKuKJFaCrdjP/qeEVWi3no10f506oGlf7koFlzsifVPJcrby5nSxWp1DtmTsK5Uf",
	"3HKupKUwkWBVFYL7b9OPJnS7QPJjEsQPneOQXKtr8j+EGvGgf7q6umT07z9c/r/EXmVyj4XIQbchEvZr",
	"bJ1jljSQ1ipobOqyRH1oGAEnpS59qoB3qraAIOkeHKuAbU0ckxPVPS098g1F2H5LNtofWDztJ+F+uiF5",
	"DYbcvK61JmmLA2jaCGNJUx43rXkqHd5EdHhLFrAooMMP2VnkcUc3x+2ybu53j1lWvl4GwbiSUerA1L49",
	"ruuiOIDBPeWLl1McSHYqsmEtVQWKPKVmJhw/vCJT40KST8zazyz91KQcsUBz5BpwNwvKB+IvKXsLExBu",
	"nJrg7lHQvwfAWmlACf1hDVDm3pJgt9RC7ppYxCNuyY/dkBp3ydk9biGHjNxNn9kdY3fWiDO8IIF17r9a",
	"9BgIwIZuCMGNAoS19tnnwFFCgbXk297KofJuWDPpg/uT/XZMu2FwrONGZ0o3LWksyZI2bPXugQmXgJug",
	"WMLCUMtCBHauX9LT4nzsfb9gI4/mERH2tn++r8nyLeXgcvnBhPklJ4uiMEvK7Zt3GzQ+8IrB6X88/h8A",
	"AP//Od768xYTAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
