// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// CategorySpend defines model for CategorySpend.
type CategorySpend struct {
	Amount     float64 `json:"amount"`
	Category   string  `json:"category"`
	Count      int     `json:"count"`
	Percentage float64 `json:"percentage"`
}

// GetSpendByCategoryResponse defines model for GetSpendByCategoryResponse.
type GetSpendByCategoryResponse struct {
	Categories    []CategorySpend `json:"categories"`
	TotalSpending float64         `json:"total_spending"`
}

// GetTransactionsResponse defines model for GetTransactionsResponse.
type GetTransactionsResponse struct {
	Transactions []Transaction `json:"transactions"`
}

// PullTransactionsRequest defines model for PullTransactionsRequest.
type PullTransactionsRequest struct {
	AccountId string `json:"account_id"`
	BankName  string `json:"bank_name"`
	DateFrom  string `json:"date_from"`
	DateTo    string `json:"date_to"`
	UserId    int    `json:"user_id"`
}

// PullTransactionsResponse defines model for PullTransactionsResponse.
type PullTransactionsResponse struct {
	Pulled int `json:"pulled"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	AccountId     string  `json:"account_id"`
	Amount        float64 `json:"amount"`
	BankName      string  `json:"bank_name"`
	Category      *string `json:"category,omitempty"`
	Date          string  `json:"date"`
	MerchantName  *string `json:"merchant_name,omitempty"`
	Name          string  `json:"name"`
	Pending       bool    `json:"pending"`
	TransactionId string  `json:"transaction_id"`
}

// GetTransactionsParams defines parameters for GetTransactions.
type GetTransactionsParams struct {
	UserId int `form:"user_id" json:"user_id"`
}

// GetSpendByCategoryParams defines parameters for GetSpendByCategory.
type GetSpendByCategoryParams struct {
	UserId int `form:"user_id" json:"user_id"`
}

// PullTransactionsJSONRequestBody defines body for PullTransactions for application/json ContentType.
type PullTransactionsJSONRequestBody = PullTransactionsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all stored transactions for a user, across all their linked accounts
	// (GET /v1/transactions)
	GetTransactions(c *gin.Context, params GetTransactionsParams)
	// Get spend grouped by category for a user, across all their linked accounts
	// (GET /v1/transactions/categories)
	GetSpendByCategory(c *gin.Context, params GetSpendByCategoryParams)
	// Pull transactions for one account over a date range and persist them
	// (POST /v1/transactions/pull)
	PullTransactions(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetTransactions operation middleware
func (siw *ServerInterfaceWrapper) GetTransactions(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTransactionsParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := c.Query("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument user_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "user_id", c.Request.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTransactions(c, params)
}

// GetSpendByCategory operation middleware
func (siw *ServerInterfaceWrapper) GetSpendByCategory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSpendByCategoryParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := c.Query("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument user_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "user_id", c.Request.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSpendByCategory(c, params)
}

// PullTransactions operation middleware
func (siw *ServerInterfaceWrapper) PullTransactions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PullTransactions(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/transactions", wrapper.GetTransactions)
	router.GET(options.BaseURL+"/v1/transactions/categories", wrapper.GetSpendByCategory)
	router.POST(options.BaseURL+"/v1/transactions/pull", wrapper.PullTransactions)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RWT2/6SAz9KqPZPUaF7p9LbtseVr2h7d6qCpnEwLST8dTjsEJVvvtqJgESSCr6U3v4",
	"3ULs2M9+zzbvuqDKk0MnQefvOhRbrCA93oPghnj/6NGV8YVn8shiMJmhotpJfFoTVyA61yXVK4s607L3",
	"qHPt6mqFrJtMF12s6N4Zg7Bxm2Q8BOosxglu2u88coFOYINXJWoyzfhWG8ZS50+nrNkB7SHZIPLzMQ6t",
	"XrCQmPhvlFT33f7Qhn8weHIBLzvRpel+GcEqPfzKuNa5/mV26vCsa+9s2NvmCACYYZ9+k4BdhmiOXfrx",
	"4iOqi3ATFf/L4AIUYsiF6XKl53V1wb3Ql+WeIR8kGIO6qK0dYn2rMciIRotE99KUo8JbgXtdOqhw1FqC",
	"4HLNVE1bhUZtdUAe5jxK+qzUg2cfS9aH3YdxSnpdU6YI9LW1eA26znEsW5/Pz7b9U5vjY44+3CuxW6OG",
	"CrnYgpPpuJOG3kB2thWRRWhVfWrKeO3TQr9CBLqD1Vtm0/McUxm3TvosMRRsfMuV/mvxEJSQiuSq/qip",
	"KDK1sGBKBa5UO4P/KdliFJ4YsTF8j3b1iLwzRcSzQw5t8Nub+c08toI8OvBG5/r39CrTHmSb1DHb3c7O",
	"d8gGkx6iiCC+fCh1fr6RUgyGCgU56PzpXZuY8q3GtOFbynoTdeq0cI1Zd9pGZf8cvdtxSXB+m8/TYicn",
	"2CoVvLemSNhmL6EV/SngR5tvaq8miobU3FO1Mg7LPi3KmpAm7o8W0/CLB7cDa0rF3QZsMv3nmF/kClkh",
	"M7VjHuqqgjg3scsKrFVBiIepg1oTK1CxpZmCgimE5CpbNKysca9Yqk6nIYU953Y2vI1TNJ+d2p+X6an/",
	"DCNkJ1e12qvjDvtmktP1Vxum2uMg8RfQHJdJugMURhg+P00dZRjkjsr9l/V/6m9BM9y7USPNhQxuvxHG",
	"tAj6fqo9t2n3tsP4nYpYXK5/YkUOD0wrip+CiqdHMbgNJmQ+7vog7WFomqb5PwAA///LJm5VQgwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
